version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js
      - npm install || { echo "npm install failed"; exit 1; }

  build:
    commands:
      - echo Build started on `date`
      - npm test || { echo "Tests failed"; exit 1; }

artifacts:
  files:
    - '**/*'
  discard-paths: yes
